version: '3.8'

services:
  dataingestion-service:
    build: ./dataingestion-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform
  datadeduplication-service:
    build: ./datadeduplication-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform
  dataquality-service:
    build: ./dataquality-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform
  datanormalization-service:
    build: ./datanormalization-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform
  datastorage-service:
    build: ./datastorage-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform
  dataconsumption-service:
    build: ./dataconsumption-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PYTHON_FASTAPI_BASE_URL=http://python-api:8000
    depends_on:
      - python-api
    networks:
      - data-platform

  python-api:
    # Python FastAPI service configuration
    image: python:3.9-slim
    ports:
      - "8000:8000"
    # Add your Python FastAPI configuration here
    networks:
      - data-platform

networks:
  data-platform:
    driver: bridge

volumes:
  data-platform-data:
